openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8082
    description: Generated server url
tags:
  - name: Article events controller
    description: API for getting article's event
paths:
  /events:
    get:
      tags:
        - Article events controller
      operationId: getAllArticleEvents
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: size
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 100
        - name: type
          in: query
          required: false
          schema:
            type: string
        - name: date
          in: query
          required: false
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Successfully retrieved page of
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ArticleEvent'
components:
  schemas:
    ArticleEvent:
      type: object
      properties:
        id:
          type: integer
          format: int64
        articleId:
          type: integer
          format: int64
        authorId:
          type: integer
          format: int64
        changeType:
          type: string
          enum:
            - CREATED
            - UPDATED
            - DELETED
        changes:
          type: array
          items:
            $ref: '#/components/schemas/Changes'
        createdAt:
          type: string
          format: date-time
      description: Details about an article event
    Changes:
      type: object
      properties:
        field:
          type: string
        newData:
          type: string
